### ISSUE TITLE
BUG: THIS IS NOT ALING WITH REACT

### ISSUE THREAD

**Issue by gemrey13** [gemrey13/paymongo-ts#1]
help me.....

**Comment by RyannKim327** [comment]
1. Create an [npmjs account](https://npmjs.com/signup)
2. Next is login with your terminal or vscode using `npm login`
3. Once you've logged in either from browser or through terminal, you may now publish your package using `npm publish`

### Note
> You may publish a single version in a project, meaning everytime you publish your project, you need to change the version on the package.json > version
